#!/usr/bin/env lua
require "guckets"
require "test.utils"

-- create the level.
level = guckets.level:new()
level.author = "penma"
level.name = "Level 1"

table.insert(level.buckets, guckets.bucket:new({ water = 0, water_max = 5 }))
table.insert(level.buckets, guckets.bucket:new({ water = 1, water_max = 3 }))

table.insert(level.goals, {
	function (level)
		return level.buckets[1] == 4
	end, "%d liters of water in bucket %d", 4, 1 })
level:auto_spare_water()

-- run tests
test.section("Checking if the autogenerated spare bucket is correct")
test.condition("Available water is 7", level.spare_bucket.water == 7)
test.condition("Maximum water not in visible buckets is 8", level.spare_bucket.water_max == 8)

test.section("Emptying bucket, rechecking spare bucket")
level.buckets[2]:pour_to(level.spare_bucket)
test.condition("Available water is 8", level.spare_bucket.water == 8)
test.condition("Bucket 2 is empty", level.buckets[2].water == 0)

test.section("Playing the level and checking the solution")
level.spare_bucket:pour_to(level.buckets[2])
level.buckets[2]:pour_to(level.buckets[1])
level.spare_bucket:pour_to(level.buckets[2])
level.buckets[2]:pour_to(level.buckets[1])
level.buckets[1]:pour_to(level.spare_bucket)
level.buckets[2]:pour_to(level.buckets[1])
level.spare_bucket:pour_to(level.buckets[2])
level.buckets[2]:pour_to(level.buckets[1])

test.condition("Bucket 1 is 4", level.buckets[1].water == 4)
test.condition("Bucket 2 is 0", level.buckets[2].water == 0)
test.condition("Available water is 4", level.spare_bucket.water == 4)

test.results()
